### ISSUE TITLE
how do you install this?

### ISSUE THREAD

**Issue by neumachen** [gwygonik/SquiggleDraw#11]
Noob on processing here. But how do you exactly install this?

**Comment by neumachen** [comment]
Never mind, my laziness has struct again. Didn't realize it's very simple to use.

**Comment by charliecwilliams** [comment]
Hey - what was the issue for you in the end? Having trouble myself.

**Comment by gwygonik** [comment]
I'm terribly sorry I missed all of these 😦  

For this to work, you need to install Processing ( http://www.processing.org ) for your OS, then download this repo. Unzip it into the "Sketchbook" location that Processing will make on your computer (open Preferences and it will show you where that location is; typically in Documents). You can then open this sketch and run it.

If you are having a different problem running it then, please let me know and I'll try to help.

**Comment by Leopain-gif** [comment]
I copied the files to Processing/libraries but when I try to run the program it tells me no library found for processing.svg.. Please help with what I need to do. I am 62 and live in South Africa and PC stuff is not easy for me.

**Comment by gwygonik** [comment]
Hi @Leopain-gif -- instead of putting the files in your libraries folder, place the folder in the same place on your computer where other sketches are saved. For example, on my Mac it's "Documents/Processing/sketches". I'm not sure, but putting it in the libraries folder might cause issues. If moving to sketches doesn't help, let us know and we'll try to get you up and running.

**Comment by Leopain-gif** [comment]
Thank you for your reply. Where would I find the sketches folder in windows 10.

**Comment by Leopain-gif** [comment]
Also tells me that "No library found for processing.svg

**Comment by Leopain-gif** [comment]
I am using Processing 2 might this be the problem.

**Comment by Leopain-gif** [comment]
Thanks for your advice.
I decided to update processing and this has done the trick finally I managed to open Siggeldraw.
Thank you

**Comment by gwygonik** [comment]
Sorry for not getting back sooner, but I'm glad you solved the problem! That's good to know what errors show up with Processing 2 so we can help people in the future. Cheers!
