### ISSUE TITLE
connect ends changes wave aglinment 

### ISSUE THREAD

**Issue by stephanschulz** [gwygonik/SquiggleDraw#14]
Thanks for this great piece of software. It is a lot of fun to work with.

I am noticing that when I select "Connect ends" the wave rows shift. 
Here are 2 images with yellow highlight to show an area where this shift is very noticeable.
I am not sure if this behaviour is intentional but thought I better share my findings.

<img width="594" alt="Screen Shot 2020-08-25 at 3 04 27 PM" src="https://user-images.githubusercontent.com/1054816/91216918-b6154280-e6e4-11ea-875f-309f7d7cf876.png">
<img width="593" alt="Screen Shot 2020-08-25 at 3 04 21 PM" src="https://user-images.githubusercontent.com/1054816/91216920-b7466f80-e6e4-11ea-9cfd-b90b42811ca7.png">

**Comment by oskay** [comment]
Confirmed.

**Comment by gwygonik** [comment]
Merged fix from oskay. Closing
