### ISSUE TITLE
Resize resolution

### ISSUE THREAD

**Issue by destroper** [gwygonik/SquiggleDraw#18]
Hello, Your software is fantastic!
However, when I load a large image (3600px) it comes out of my screen and I cannot resize the window to see the preview.
Do you have a solution to this?

**Comment by destroper** [comment]
i just saw the oskay commit, it doesn't work, what should i do?
thank you in advance

**Comment by oskay** [comment]
> i just saw the oskay commit, it doesn't work

Can you please say _what_ exactly I did that isn't working?

**Comment by destroper** [comment]
I attach a screen.
When I load a large image (larger than my screen) I cannot see the entire image.
My instinctive manipulation is to reduce the size of the window (and have a scale of the preview image) but it's impossible to reach the bottom corners of the window.
I saw issue # 15, and thought it was the solution, but no. The size of the image is therefore limited to the size of the screen? (visually)

![Capture](https://user-images.githubusercontent.com/66673462/106588424-0d98c380-654b-11eb-9adc-ff7c926ccdb7.PNG)

**Comment by oskay** [comment]
Issue #15 is unrelated to this. I'd suggest that you resize your image, as the easiest way to work with what this program currently does.

**Comment by gwygonik** [comment]
Going to close since this is <gulp> years old! However, I'll add that the new Inkscape-native version of SquiggleDraw (see: https://github.com/gwygonik/SquiggleDrawInkscape) _should_ work better for larger images. 😃
