### ISSUE TITLE
Invert control not working properly?

### ISSUE THREAD

**Issue by oskay** [gwygonik/SquiggleDraw#2]
The invert control appears to crash the program.

**Comment by gwygonik** [comment]
I wonder if this is a memory issue in Processing? I haven't been able to get it to crash with the invert control, but was able to run out of memory when scaling the sample image up 4x (I capped slider at 3x).

Is there any output in the Processing console when it crashes?

**Comment by oskay** [comment]
I've been able to get it to crash (same way, I think) pressing Invert, or by loading larger images. 

"An OutOfMemoryError means that your code is either using up too much memory
because of a bug (e.g. creating an array that's too large, or unintentionally
loading thousands of images), or that your sketch may need more memory to run.
If your sketch uses a lot of memory (for instance if it loads a lot of data files)
you can increase the memory available to your sketch using the Preferences window."

Using a Mac, default memory settings.

Although, it isn't crashing from the inversion (at least on the default image) at present. Something in the last few commits must have helped.

**Comment by gwygonik** [comment]
Hrm. The way I'm (probably unnecessarily) creating a second image to use for pixel scraping definitely can make large images. I'll see if I can redo this so it doesn't need the larger image.

**Comment by oskay** [comment]
It seems likely that one could just reference p1, with a divisor instead.

**Comment by gwygonik** [comment]
Yeah - I really can't remember why I did it this way... it was three years ago ;-) I think I wanted the SVG to be a specific size for my WCB, and couldn't get Processing to cooperate. I'll dig into it more soon, but _should_ be doable.

**Comment by gwygonik** [comment]
Since this isn't an issue with Invert per-se, I'm closing this issue, but have opened a new one ( #5 ) to look at consuming less memory all-up.
