### ISSUE TITLE
Re-work image handling to use less memory

### ISSUE THREAD

**Issue by gwygonik** [gwygonik/SquiggleDraw#5]
Without changing the memory limits in Processing's Preferences, it is possible to run out of memory through a combination of parameters (many lines, high image resolution scale, etc).

Re-work the way images are are loaded and squiggles created to use less memory - if possible.

Note that initial attempts (as suggested in #2 ) have proven only slightly better for memory usage and haven't produced quite the same output quality. :-(

**Comment by oskay** [comment]
Is this still an issue?

**Comment by gwygonik** [comment]
Haven't seen the problem and no one has +1'd it... Closing
